### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by Pieprzyk** [Manevolent/ts3j#16]
lut 16, 2020 12:13:42 AM com.github.manevolent.ffmpeg4j.FFmpegIO$1 call
WARNING: Problem in FFmpeg IO read id=2
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.MeteredStream.read(MeteredStream.java:134)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3336)
	at com.github.manevolent.ffmpeg4j.FFmpegIO$1.call(FFmpegIO.java:139)
	at org.bytedeco.javacpp.avformat.av_read_frame(Native Method)
	at com.github.manevolent.ffmpeg4j.stream.source.FFmpegSourceStream.readPacket(FFmpegSourceStream.java:131)
	at com.github.manevolent.ffmpeg4j.source.FFmpegAudioSourceSubstream.read(FFmpegAudioSourceSubstream.java:105)
	at com.github.manevolent.ffmpeg4j.source.MediaSourceSubstream.next(MediaSourceSubstream.java:63)

**Comment by Manevolent** [comment]
Hi @Pieprzyk,
This error is not due to handling in ts3j.  This is due to a connection reset in the SSL connection between your application and the remote endpoint where you are receiving data from.
If this is a YouTube connection, you will need to avoid keep connections open for long periods of time.  This is something I addressed in Manebot last month.

For any issues related specifically to ffmpeg4j (technically, this is not), please file issues on that project.

Thanks

**Comment by Pieprzyk** [comment]
+1 
Thanks, it works.
