### ISSUE TITLE
Encryption error after connect

### ISSUE THREAD

**Issue by Pieprzyk** [Manevolent/ts3j#18]
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransf
ormation, state=RETRIEVING_DATA, id=172, generation=1
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
        ... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
        at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
        at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
        ... 3 more
java.lang.Exception: Problem reading COMMAND
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransf
ormation, state=RETRIEVING_DATA, id=173, generation=1
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
        ... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
        at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
        at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
        ... 3 more
java.lang.Exception: Problem reading COMMAND
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransf
ormation, state=RETRIEVING_DATA, id=162, generation=1
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
        ... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
        at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
        at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
        ... 3 more
java.lang.Exception: Problem reading COMMAND
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransf
ormation, state=RETRIEVING_DATA, id=163, generation=1
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
        ... 2 more

**Comment by Manevolent** [comment]
Please supply more details with tickets instead of sending only stack traces.  For example, what server version are you trying to connect to?  Is it a genuine Teamspeak3 server?  Otherwise, I have no hope of reproducing the issue.

**Comment by Pieprzyk** [comment]
3.11.0 on Linux licensed ts3 server

**Comment by Pieprzyk** [comment]
Using this version of bcprov-jdk15on-1.60.jar

**Comment by Pieprzyk** [comment]
Application runned on linux OS debian 10

**Comment by Pieprzyk** [comment]
Problem starts while server is sending packet with type COMMAND and length = 11 other packets goes with a right way. Any ideas how to fix it?


[NETWORK] READ COMMAND id=289 len=500 from /178.217.186.143:9987
[NETWORK] READ COMMAND id=290 len=237 from /178.217.186.143:9987
[NETWORK] READ COMMAND id=291 len=500 from /178.217.186.143:9987
[NETWORK] READ COMMAND id=164 len=230 from /178.217.186.143:9987
java.lang.Exception: Problem reading COMMAND id= 164 len= 11
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:656)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:949)
        at java.lang.Thread.run(Thread.java:748)
[NETWORK] READ COMMAND id=165 len=500 from /178.217.186.143:9987
java.lang.Exception: Problem reading COMMAND id= 165 len= 11
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:656)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:949)
        at java.lang.Thread.run(Thread.java:748)
[NETWORK] READ COMMAND id=166 len=132 from /178.217.186.143:9987
java.lang.Exception: Problem reading COMMAND id= 166 len= 11
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:656)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:949)
        at java.lang.Thread.run(Thread.java:748)
[NETWORK] READ COMMAND id=167 len=500 from /178.217.186.143:9987
java.lang.Exception: Problem reading COMMAND id= 167 len= 11
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:656)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:949)
        at java.lang.Thread.run(Thread.java:748)
[NETWORK] READ COMMAND id=168 len=181 from /178.217.186.143:9987
java.lang.Exception: Problem reading COMMAND id= 168 len= 11
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:656)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:949)
        at java.lang.Thread.run(Thread.java:748)
[NETWORK] READ COMMAND id=169 len=500 from /178.217.186.143:9987
java.lang.Exception: Problem reading COMMAND id= 169 len= 11
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:656)
        at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:949)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Manevolent** [comment]
I am on vacation through this week, however based on you logs I do have one takeaway.  Teamspeak3 always sends a packet number (ID) with every packet, incremented by one for each packet.  This ensures orderly, sequential reception of packets.  This field is 16 bits, so the highest theoretical packet number is 2^16 - 1; 65,535 or so.  

When this large number is reached, both the client and server will start over at 0 for their packet IDs.  

In your case, you are jumping from about 200 to roughly 160.  This is very unusual behavior, and not something I have seen before.  TeamSpeak has some weird behavior in their protocol, and perhaps this is something they recently changed to mess with projects like TS3j.. It'll be hard for me to tell until I have a chance to test this on my own.

It's possible Splamy's TS3 implementation and that community has already bumped into this before, and we could save some time by seeing if any issues existed over there that match this description.  If not, this could be a genuine bug in my protocol handling that's existed for some time.

**Comment by Pieprzyk** [comment]
The most weird thing is that application is running without any error while it's runned on windows OS and generate exceptions on linux

**Comment by Flakebi** [comment]
As far as I know nothing changed in the low-level protocol. At least the TS3AudioBot connects fine to 3.11.0 servers.
You need to send an up-to-date "version" in the low-level handshake, but as far as I remember you do that.

**Comment by Pieprzyk** [comment]
Fixed :D 🏆

**Comment by Pieprzyk** [comment]
Before 
            // Get packet generation
            RemoteCounter counter = remoteSendCounter.get(networkPacket.getHeader().getType());
            int generation = 0;
            if (counter != null) {
                generation = counter.getGeneration(networkPacket.getHeader().getPacketId());
            }
            networkPacket.getHeader().setGeneration(generation);

            // Read packet (decrypt, decompress, etc)
            Packet packet;
            try {
                packet = readPacketIntl(networkPacket);
            } catch (Exception ex) {
                exceptionHandler.accept(new Exception("Problem reading " + networkPacket.getHeader().getType().name()+" id= "+networkPacket.getHeader().getPacketId() +" len= "+networkPacket.getHeader().getSize()));
                continue;
            }

// Read packet (decrypt, decompress, etc)
            Packet packet;
            try {
                packet = readPacketIntl(networkPacket);
            } catch (Exception ex) {
                exceptionHandler.accept(new Exception("Problem reading " + networkPacket.getHeader().getType().name()+" id= "+networkPacket.getHeader().getPacketId() +" len= "+networkPacket.getHeader().getSize()));
                continue;
            }

After
            // Get packet generation
            RemoteCounter counter = remoteSendCounter.get(networkPacket.getHeader().getType());
            int generation = 0;
            if (counter != null) {
                generation = counter.getGeneration(networkPacket.getHeader().getPacketId());
            }
            networkPacket.getHeader().setGeneration(generation);
