### ISSUE TITLE
Can´t connect to a TeaSpeak server

### ISSUE THREAD

**Issue by lexesv** [Manevolent/ts3j#2]
```
[DEBUG] Improved identity security level: from 0 to 2 (0)
[DEBUG] Improved identity security level: from 2 to 6 (1)
[DEBUG] Improved identity security level: from 6 to 9 (2)
[DEBUG] Connecting to /178.32.109.167:11079...
[DEBUG] State changing: CONNECTING
[DEBUG] State changed: CONNECTING
[DEBUG] Assigning com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerConnecting handler...
[DEBUG] [PROTOCOL] WRITE INIT1
[DEBUG] [NETWORK] WRITE INIT1 id=101 len=34 to /178.32.109.167:11079
[DEBUG] Assigned com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerConnecting handler.
[DEBUG] [NETWORK] READ INIT1 id=101 len=32 from /178.32.109.167:11079
[DEBUG] [PROTOCOL] READ INIT1
[DEBUG] [PROTOCOL] WRITE INIT1
[DEBUG] [NETWORK] WRITE INIT1 id=101 len=38 to /178.32.109.167:11079
[DEBUG] [NETWORK] READ INIT1 id=101 len=244 from /178.32.109.167:11079
[DEBUG] [PROTOCOL] READ INIT1
[DEBUG] [PROTOCOL] WRITE INIT1
[DEBUG] [NETWORK] WRITE INIT1 id=101 len=484 to /178.32.109.167:11079
[DEBUG] [NETWORK] READ COMMAND id=0 len=182 from /178.32.109.167:11079
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=0
[DEBUG] [PROTOCOL] READ COMMAND
[DEBUG] [PROTOCOL] ENCRYPT ACK generation=0
[DEBUG] [PROTOCOL] WRITE ACK
[DEBUG] [NETWORK] WRITE ACK id=1 len=15 to /178.32.109.167:11079
[DEBUG] [PROTOCOL] REASSEMBLE COMMAND id=0 len=179
[DEBUG] State changing: DISCONNECTED
[DEBUG] State changed: DISCONNECTED
[DEBUG] Assigning com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerDisconnected handler...
[DEBUG] Assigned com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerDisconnected handler.
java.util.concurrent.TimeoutException: timeout waiting for CONNECTED state
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.waitForState(AbstractTeamspeakClientSocket.java:248)
	at com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket.connect(LocalTeamspeakClientSocket.java:313)
	at main.Controller.handleConnect(Controller.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
```

**Comment by lexesv** [comment]
1.2.17-beta-7

**Comment by lexesv** [comment]
If on the server no users, the bot connected normal. Otherwise, this error occurs.
After connecting the bot, I connect to the server and see it.

**Comment by Manevolent** [comment]
That sounds like an issue with the server.  Given I was able to construct connections to the IP/port in the source, tear down (disconnect), and reconnect w/o issue, I would start with server configuration and look into that -- try changing HWID as well, you can randomize that to any string you like.

**Comment by lexesv** [comment]
Thanks for reply. I try it.

**Comment by lexesv** [comment]
I was try set different options but I get the error: too many clones already connected.
I saw you were connecting to the server. Tell me, what settings did you apply?

**Comment by Lumafiziert** [comment]
Uhm i'm trying to connect as the wiki says

```
client.connect(new InetSocketAddress(
        InetAddress.getByName(address),
        port // UDP client port, Teamspeak3 client uses 9987
   ), null, 10000L); 
```

but its not working
