### ISSUE TITLE
mac check in EAX failed

### ISSUE THREAD

**Issue by WrightBlue** [Manevolent/ts3j#26]
```
[DEBUG] [NETWORK] READ COMMAND id=208 len=285 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=208, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=212 len=216 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=212, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=213 len=500 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=213, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=216 len=229 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=216, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=217 len=500 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=217, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=221 len=500 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=221, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=224 len=274 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=224, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=225 len=500 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=225, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=227 len=500 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=227, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=228 len=262 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=228, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=229 len=500 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=229, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=230 len=239 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=230, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ COMMAND id=233 len=500 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] DECRYPT COMMAND generation=1
java.lang.Exception: Problem reading COMMAND
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:657)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: failed to decrypt COMMAND (transformation=class com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation, state=RETRIEVING_DATA, id=233, generation=1
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:564)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:654)
	... 2 more
Caused by: org.bouncycastle.crypto.InvalidCipherTextException: mac check in EAX failed
	at org.bouncycastle.crypto.modes.EAXBlockCipher.doFinal(Unknown Source)
	at com.github.manevolent.ts3j.protocol.packet.transformation.PacketTransformation.decrypt(PacketTransformation.java:146)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacketIntl(AbstractTeamspeakClientSocket.java:550)
	... 3 more
[DEBUG] [NETWORK] READ VOICE id=186 len=124 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] READ VOICE
[DEBUG] [NETWORK] READ VOICE id=187 len=132 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] READ VOICE
[DEBUG] [NETWORK] READ VOICE id=188 len=134 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] READ VOICE
[DEBUG] [NETWORK] READ VOICE id=189 len=130 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] READ VOICE
[DEBUG] [NETWORK] READ VOICE id=190 len=134 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] READ VOICE
[DEBUG] [NETWORK] READ VOICE id=191 len=137 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] READ VOICE
[DEBUG] [NETWORK] READ VOICE id=192 len=137 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] READ VOICE
[DEBUG] [NETWORK] READ VOICE id=193 len=137 from /178.217.188.55:9987
[DEBUG] [PROTOCOL] READ VOICE
[DEBUG] State changing: DISCONNECTED
[DEBUG] State changed: DISCONNECTED
[DEBUG] Assigning class com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerDisconnected handler...
[DEBUG] Assigned class com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerDisconnected handler.
Exception in thread "main" java.util.concurrent.TimeoutException: timeout waiting for CONNECTED state
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.waitForState(AbstractTeamspeakClientSocket.java:264)
	at com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket.connect(LocalTeamspeakClientSocket.java:396)
	at com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket.connect(LocalTeamspeakClientSocket.java:339)
	at com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket.connect(LocalTeamspeakClientSocket.java:316)
	at blue.wright.serverlistbot.Main.main(Main.java:38)
java.io.IOException: disconnected
	at com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket.readNetworkPacket(LocalTeamspeakClientSocket.java:247)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.readPacket(AbstractTeamspeakClientSocket.java:628)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkReader.run(AbstractTeamspeakClientSocket.java:952)
	at java.lang.Thread.run(Thread.java:748)
```

Tested on:

```
3.12.1 on Linux licensed TeamSpeak 3 server
Debian GNU/Linux 9.13 (stretch)
openjdk version "1.8.0_252"
```

Code:

```java
    public static void main(String[] args) throws Exception {
        Ts3Debugging.setEnabled(true);
        LocalTeamspeakClientSocket client = new LocalTeamspeakClientSocket();
        LocalIdentity identity = LocalIdentity.read(new File("identity.ini"));
        client.setIdentity(identity);
        client.setNickname("plswork:(");
        client.setHWID('plssssswork');
        client.addListener(new TS3Listener() {
            @Override
            public void onDisconnected(DisconnectedEvent e) {
                System.exit(-1);
            }
        });
        client.setClientVersion("Linux", "3.5.5 [Build: 1594213121]", "qcElldtu07fZwpqJibMXCuGjdzgk1W+bHOmtrMRQzUEo+qxkETaR/dUpUqrF3WUKQ0XC58E0wG584toQGk2jBA==");
        client.connect("ts3.black", 5000L);
    }
```

**Comment by Manevolent** [comment]
I've connected TS3j to a `3.12.1 on Linux` server without issue; that server is watchtower'd and auto-updates on Docker.  I'm wondering if there is a compatibility issue here.  Is the behavior any different if you don't set a client version string?

**Comment by WrightBlue** [comment]
If I connect to an empty server in version 3.12.1 on Linux everything works, and if I connect to ts3.black (200+ users online) I get this error.

**Comment by Manevolent** [comment]
Given the user count, this seems a lot like a similar problem I found with compression in #12.  Maybe the cryptography routines suffer from similar "large" packet bugs?  Looking at your logs more closely, your packet ID's jump by 3 ID's or more semi-regularly... that's really odd.  Granted, you could be dealing with out-of-order delivery and/or packet loss, but I'm seeing:

```
208 received
(209, 210, 211 missed)
212, 213 received
(214, 215 missed)
216, 217 received
(218, 219, 220 missed)
221 received
(222, 223 missed)
224, 225 received
(226 missed)
227, 228, 229, 230 received
(231, 232 missed)
233 received
```

(Did you remove those from your logs?  If so, did those de-crypt OK?)

I'll have to take a deeper dive, specifically into the server you're on.  When do the errors start?  Is it at a specific point in the packet stream?  Some of any "healthy" traffic you have would be helpful.
