### ISSUE TITLE
client is modified error

### ISSUE THREAD

**Issue by mistergoliath41** [Manevolent/ts3j#27]
`[DEBUG] Problem reading packet
java.io.IOException: com.github.manevolent.ts3j.command.CommandProcessException: client is modified
	at com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerFull.handlePacket(LocalClientHandlerFull.java:40)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkHandler.run(AbstractTeamspeakClientSocket.java:935)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.github.manevolent.ts3j.command.CommandProcessException: client is modified
	at com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerRetrievingData.handleCommand(LocalClientHandlerRetrievingData.java:24)
	at com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerFull.handlePacket(LocalClientHandlerFull.java:35)
	... 2 more
java.io.IOException: com.github.manevolent.ts3j.command.CommandProcessException: client is modified
	at com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerFull.handlePacket(LocalClientHandlerFull.java:40)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket$NetworkHandler.run(AbstractTeamspeakClientSocket.java:935)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.github.manevolent.ts3j.command.CommandProcessException: client is modified
	at com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerRetrievingData.handleCommand(LocalClientHandlerRetrievingData.java:24)
	at com.github.manevolent.ts3j.protocol.packet.handler.client.LocalClientHandlerFull.handlePacket(LocalClientHandlerFull.java:35)
	... 2 more`

**Comment by Manevolent** [comment]
This usually happens if your client version name string and signature string don't match cryptographically, at least according to the server.  What code are you using to connect?

**Comment by mistergoliath41** [comment]
> This usually happens if your client version name string and signature string don't match cryptographically, at least according to the server. What code are you using to connect?
3.5.3 [Build: 1586353391],Windows,knmVmUvvQTTfOUCWlQncjWFWHXFqZMntUbIPIi/YLcxdW4iP3woJQgVTaIZPEiluMT5A7tb2lSk/r+Byh5R6Dw==

**Comment by Manevolent** [comment]
I took a look at the source code I have on my end, and this version signature doesn't seem to match what I have in the repository by default (https://github.com/Manevolent/ts3j/search?q=3.5.3&unscoped_q=3.5.3).  If you are using your own version signature, please make sure it is valid -- there is only one "key" (in your case, your key/signature is `knmVmUvvQTTfOUCWlQncjWFWHXFqZMntUbIPIi/YLcxdW4iP3woJQgVTaIZPEiluMT5A7tb2lSk/r+Byh5R6Dw==`) for a given "build" (`3.5.3 [Build: 1586353391],Windows`).  These are signed by TeamSpeak.  I suggest either using the default version signature in TS3j or using one that is correct.

**Comment by mistergoliath41** [comment]
I have the same error with the default key of TS3j. :/
