### ISSUE TITLE
Unable to send long Cyrillic messages to chat

### ISSUE THREAD

**Issue by nodamnway** [Manevolent/ts3j#30]
I am unable to send long messages in Cyrillic(>215 chars).

```java
        client.sendChannelMessage(
                client
                        .getClientInfo(client.getClientId())
                        .getChannelId(),
                StringUtils.repeat("ы", 216)
        );
```

Its resulting packet exceeds `MAXIMUM_PACKET_SIZE=500` thus it will be sent [fragmented](https://github.com/Manevolent/ts3j/blob/25a7c94596d63727a20b6e869ea5af5c07e88019/src/main/java/com/github/manevolent/ts3j/protocol/socket/client/AbstractTeamspeakClientSocket.java#L338).

Unfortunately it does not work as expected:

```
Exception in thread "main" java.util.concurrent.TimeoutException: send
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.writePacketIntl(AbstractTeamspeakClientSocket.java:513)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.writePacket(AbstractTeamspeakClientSocket.java:350)
	at com.github.manevolent.ts3j.protocol.socket.client.AbstractTeamspeakClientSocket.writePacket(AbstractTeamspeakClientSocket.java:322)
	at com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket$ClientCommandResponse.ensureSent(LocalTeamspeakClientSocket.java:742)
	at com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket.sendCommand(LocalTeamspeakClientSocket.java:579)
	at com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket.executeCommand(LocalTeamspeakClientSocket.java:507)
	at com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket.executeCommand(LocalTeamspeakClientSocket.java:469)
	at com.github.manevolent.ts3j.protocol.socket.client.LocalTeamspeakClientSocket.sendChannelMessage(LocalTeamspeakClientSocket.java:1094)
	at playground.sender.LongSendFail.main(LongMessagwSendFail.java:34)
```

Same message can be sent with official TS3 client.

**Comment by kjzl** [comment]
NEW_PROTOCOL flag must be included in all parts of the split packet as stated here:
https://github.com/ReSpeak/tsdeclarations/blob/master/ts3protocol.md#15-packet-splitting

adding the following somewhere above Line 78 fixes the issue
```java
// All parts should have NEW_PROTOCOL flag if original Packet has it
                piece.getHeader().setPacketFlag(HeaderFlag.NEW_PROTOCOL, packet.getHeader().getPacketFlag(HeaderFlag.NEW_PROTOCOL));
```

**Comment by Manevolent** [comment]
Thanks, @kjzl .  I'd appreciate a pull request with that change!  I might be able to get to it otherwise in time.
